models:
  embeddings:
    local_default:
      provider: sentence_transformers
      family: EmbeddingGemma
      hf_repository: google/embeddinggemma-300m
      revision: 57c266a740f537b4dc058e1b0cda161fd15afa75
      version: embeddinggemma-v1
      dimension: 768
  rerankers:
    local_default:
      provider: sentence_transformers
      family: BGE Reranker v2 M3
      hf_repository: BAAI/bge-reranker-v2-m3
      revision: 953dc6f6f85a1b2dbfca4c34a2796e7dde08d41e
      version: bge-reranker-v2-m3-953dc6f
